### ISSUE TITLE
Update Version Number for 1.5.7

### ISSUE THREAD

**Issue by vivekanand1117** [lpechacek/cpuset#22]
I have downloaded and installed cset 1.5.7 but it is still showing 1.5.6 when I am doing "cset -v".
Can you please update version number for the latest version?

**Comment by lpechacek** [comment]
Sure.  Fixed with 058ec1d4b9fc.  As the version string needed fixing in more places I created v1.5.8 with proper tagging.  Thanks for the bug report!

Unfortunately, I saw your pull request only after pushing out my changes.  I'm sorry for taking away the possibility to merge your patch.  I hope it won't discourage you from future contributions.

... will read all e-mail before updating the repo next time. :)

**Comment by vivekanand1117** [comment]
Not at all a problem, though it was my first patch :)
Thanks for bug fix.

**Comment by lpechacek** [comment]
I managed to merge the commit in the end.  Your trace in cyberspace will not vanish! :)

**Comment by vivekanand1117** [comment]
Thanks :)

On Mon, Mar 7, 2016 at 7:06 PM, Libor Pecháček <notifications@github.com>
wrote:

> I managed to merge the commit in the end. Your trace in cyberspace will
> not vanish! :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lpechacek/cpuset/issues/22#issuecomment-193250678>.
>



-- 
Warm Regards:

*Vivekanand *
Senior Software Dovelopment Engineer
Kritikal SecureScan Pvt. Ltd.
Noida, (U.P.)
Mob.- +91*9716346974*
